name: blog rss feed
on:
  # Schedule updates (twice a day)
  schedule: [{cron: "0 0,12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: yashkarthik
          template: classic
          base: ""
          filename: "metrics-rss"
          config_timezone: UTC
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.yashkarthik.xyz/feed.xml
